name: Siri Shortcut

on: repository_dispatch  

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
        working-directory: ./.github/issues-autolabeler
      - name: luis_label
        uses: ./.github/issues-autolabeler
        with:
          issue: ${{github.event.client_payload.description}}
        env:
          LUIS_APP_ID: ${{ secrets.LUIS_APP_ID }}
          LUIS_APP_KEY: ${{ secrets.LUIS_APP_KEY }}
      - name: create_issue
        uses: actions/github-script@0.3.0
        env:
          owner: ${{ github.actor }}
          body: ${{ github.event.client_payload.description }}
          repository: ${{ github.repository }}
        with:
          github-token: ${{github.token}}
          script: |
            const { body, owner, repository } = process.env;
            const title = "New issue report";
            const user_repo = repository.split('/');
            github.issues.create({ owner, repo: user_repo[1], title, body, labels: [process.env.ISSUE_LABEL] })
